package common;

public enum MessageType {

    HELLO, WELCOME, ERROR, BYE,LOG_EVENT,
    ROLL_DICE, BUY_PROPERTY, BID, PROPOSE_TRADE, ACCEPT_TRADE, REJECT_TRADE,
    BUILD, MORTGAGE, UNMORTGAGE, JAIL_PAY_FINE, JAIL_TRY_DOUBLE, UNDO, REDO, END_TURN,
    ACK, STATE_UPDATE, EVENT_LOG, AUCTION_STATE,SERVER_FULL,JAIL_ACTION,
    REPORT_TOPK, REPORT_PROPERTIES_UNDER_PRICE
}

